/** PHẢI khớp `User_Notif_Type` ở BE (nonj_be/src/user_notif/enum/user_notif.enum.ts) */
export enum User_Notif_Type {
    // Nhóm
    NEW_POST = 'NEW_POST',
    GRADED_POST = 'GRADED_POST',
    GROUP_JOIN_REQUEST = 'GROUP_JOIN_REQUEST',
    GROUP_JOIN_APPROVED = 'GROUP_JOIN_APPROVED',
    GROUP_JOIN_REJECTED = 'GROUP_JOIN_REJECTED',
    GROUP_MEMBER_KICKED = 'GROUP_MEMBER_KICKED',
    GROUP_MEMBER_ROLE_CHANGED = 'GROUP_MEMBER_ROLE_CHANGED',

    // Bạn bè
    FRIEND_REQUEST = 'FRIEND_REQUEST',
    FRIEND_RESPONSE = 'FRIEND_RESPONSE',

    // Khác
    SUBMISSION = 'SUBMISSION',
    REPORT_RESOLVED = 'REPORT_RESOLVED',
    REPORT = 'REPORT',
    SYSTEM = 'SYSTEM',
}
